apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
  labels:
    app: insecure-pod
spec:
  containers:
    - name: insecure-container
      image: ubuntu:24.04
      command: ["sleep", "3600"]
      securityContext:
        privileged: true
